my_ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('', views.show_all_products, name='show_products'),
    path('product/<int:pk>/', views.product_detail, name='product_detail')
]

products/models.py
from datetime import datetime
from django.db import models


class Product(models.Model):
    image = models.ImageField(null=False, blank=False)
    name = models.CharField(max_length=255, null=False, blank=False)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    description = models.TextField()
    is_published = models.BooleanField(default=True)
    created_at = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return self.name

products/views.py
from django.shortcuts import render
from .models import Product


def show_all_products(request):
    products = Product.objects.all()
    context = {'products': products}
    return render(request, 'products/show_products.html', context)


def product_detail(request, pk):
    product = Product.objects.get(id=pk)
    context = {'product': product}
    return render(request, 'products/product_detail.html', context)

products/templates/products/add_product.html
{% extends 'products/base.html' %}

{% block content %}
<h3>Add product</h3>
{% endblock content %}

products/templates/products/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Wosk i knot</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>
<body>

<h2 class="text-center mt-2">Produkty</h2>

{% block content %}

{% endblock content %}

</body>
</html>

products/templates/products/delete_product.html
{% extends 'products/base.html' %}

{% block content %}
<h3>Delete product</h3>
{% endblock content %}

products/templates/products/product_detail.html
{% extends 'products/base.html' %}

<!--    <div class="container">-->
<!--        <a style='float:left;' href="{% url 'products:show_products' %}" class="btn btn-secondary">Powrót</a>-->
<!--              <div class="card mb-3" style="width: 18rem;">-->
<!--                  <img src="{{ product.image.url }}" class="card-img-top" alt="Card image tap">-->
<!--                  <div class="card-body">-->
<!--                    <h5 class="card-title m-1">{{ product.name }}</h5>-->
<!--                    <h5 class="card-subtitle m-1">{{ product.price }} zł</h5>-->
<!--                    <p class="card-text m-1">{{ product.description|linebreaks }}</p>-->
<!--                  </div>-->
<!--              </div>-->
<!--    </div>-->


{% block content %}
<div class="container">
    <a href="{% url 'products:show_products' %}" class="btn btn-secondary mx-3 my-3">&laquo; Powrót</a>
    <div class="card text-center" xmlns:width="http://www.w3.org/1999/xhtml">
      <div class="card-body">
        <h3 class="card-title">{{ product.name }}</h3>
        <img class="img-fluid rounded" src="{{ product.image.url }}" style="width:400px;height:500px;" alt="Card image tap">
        <h5 class="card-subtitle m-1">{{ product.price }} zł</h5>
        <p class="card-text">{{ product.description|linebreaks }}</p>
        <a href="#" class="btn btn-secondary">Do koszyka &raquo;</a>
      </div>
    </div>
</div>


<!--<div class="card mb-3" style="max-width: 540px;">-->
<!--  <div class="row g-0">-->
<!--    <div class="col-md-4">-->
<!--      <img src="{{ product.image.url }}" class="img-fluid rounded-start" alt="...">-->
<!--    </div>-->
<!--    <div class="col-md-8">-->
<!--      <div class="card-body">-->
<!--        <h3 class="card-title">{{ product.name }}</h3>-->
<!--        <p class="card-text">{{ product.description|linebreaks }}</p>-->
<!--        <p class="card-text"><small class="text-muted">{{ product.price }} zł</small></p>-->
<!--        <a href="#" class="btn btn-secondary">Do koszyka</a>-->
<!--      </div>-->
<!--    </div>-->
<!--  </div>-->
<!--</div>-->
{% endblock content %}

products/templates/products/show_products.html
{% extends 'products/base.html' %}

{% block content %}

{% if products %}

    <div class="container">
        <div class="row row-cols-1 row-cols-md-3 g-4">

        {% for product in products %}
            <div class="col">
              <div class="card m-3" style="width: 18rem;">
                  <img src="{{ product.image.url }}" class="card-img-top" alt="...">
                  <div class="card-body">
                    <h5 class="card-title m-1">{{ product.name }}</h5>
                    <h5 class="card-subtitle m-1">{{ product.price }} zł</h5>
                    <a style='float:right;' href="{% url 'products:product_detail' product.id %}" class="btn btn-secondary">Szczegóły &raquo;</a>
                  </div>
              </div>
            </div>
        {% endfor %}
        </div>
    </div>

{% else %}
    <p>Obecnie nie ma żadnych produktów.</p>
{% endif %}

{% endblock content %}